ymil error checking

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,3 +14,6 @@ jobs:
 
     - name: Run a test
       run: echo "done"
+
+    - name: Error checking
+      run: echo "failed to run."; exit 1
